---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

install:
  - npm config set spin false
  - npm run setup
  - bower --version
  - phantomjs --version
